name: Deploy Landing with Maps API Key

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # 1) Clonamos el repo en $GITHUB_WORKSPACE
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Debug (listamos para comprobar que estamos en el sitio correcto)
      - name: List workspace (debug)
        run: |
          echo "📂 PWD: $(pwd)"
          ls -R .

      # 3) Inyectamos la API Key y copiamos los ficheros a public/
      - name: Inject Maps API Key & collect assets
        run: |
          mkdir -p public
          # reemplazamos el placeholder __MAPS_API_KEY__ por el secreto real
          sed "s|__MAPS_API_KEY__|${{ secrets.MAPS_API_KEY }}|g" index.html > public/index.html
          # copiamos CSS e imágenes
          cp style.css logo.png favicon.png public/

      # 4) Verificamos que public/index.html ya trae la clave
      - name: Verify injection
        run: |
          echo "🔍 Preview public/index.html:"
          head -n 3 public/index.html

      # 5) Publicamos con peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # este token ya lo inyecta GitHub automáticamente
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # muy importante: que coincida con donde creamos public/
          publish_dir: ./public
